# This is a basic workflow to help you get started with Actions

name: Github Terrafrom action demo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ARM_SUBSCRIPTION_ID: '004205ae-f333-45fb-9540-48aaa01a6e82'
      ARM_TENANT_ID: '7f4afdcb-b5ee-4dbf-979f-2cb8752be6cc'
      ARM_CLIENT_ID: 'daf8dfaa-216a-4b6e-9afb-d95b618343d0'
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_STORAGE: 'admasoft8383'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: Run Terrafrom build script
        run: chmod +x ./tfstate.sh && ./tfstate.sh ${{ env.AZURE_STORAGE }}
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: Terrafrom init
        run: terrafrom init -backend-config="storage_account_name=${{ env.AZURE_STORAGE }}"
        
      - name: Terrafrom plan
        run: terrafrom plan -out=tfplan
        
      - name: Terrafrom apply
        run: terrafrom apply tfplan

      
